/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gaps_hairengine_HairEngine */

#ifndef _Included_com_gaps_hairengine_HairEngine
#define _Included_com_gaps_hairengine_HairEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gaps_hairengine_HairEngine
 * Method:    initEngineHE
 * Signature: (Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_com_gaps_hairengine_HairEngine_initEngineHE
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_gaps_hairengine_HairEngine
 * Method:    setImageHE
 * Signature: (ILandroid/graphics/Bitmap;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gaps_hairengine_HairEngine_setImageHE
  (JNIEnv *, jobject, jint, jobject, jstring);

/*
 * Class:     com_gaps_hairengine_HairEngine
 * Method:    addStrokeHE
 * Signature: (III[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_gaps_hairengine_HairEngine_addStrokeHE
  (JNIEnv *, jobject, jint, jint, jint, jfloatArray);

/*
 * Class:     com_gaps_hairengine_HairEngine
 * Method:    clearStrokeHE
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gaps_hairengine_HairEngine_clearStrokeHE
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_gaps_hairengine_HairEngine
 * Method:    finishStrokeHE
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gaps_hairengine_HairEngine_finishStrokeHE
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_gaps_hairengine_HairEngine
 * Method:    finishStrokeStep1HE
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gaps_hairengine_HairEngine_finishStrokeStep1HE
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_gaps_hairengine_HairEngine
 * Method:    finishStrokeStep2HE
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gaps_hairengine_HairEngine_finishStrokeStep2HE
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_gaps_hairengine_HairEngine
 * Method:    initViewerHE
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gaps_hairengine_HairEngine_initViewerHE
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_gaps_hairengine_HairEngine
 * Method:    closeViewerHE
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gaps_hairengine_HairEngine_closeViewerHE
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_gaps_hairengine_HairEngine
 * Method:    resizeViewerHE
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gaps_hairengine_HairEngine_resizeViewerHE
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_gaps_hairengine_HairEngine
 * Method:    setHairDirHE
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gaps_hairengine_HairEngine_setHairDirHE
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_gaps_hairengine_HairEngine
 * Method:    setTransformHE
 * Signature: (IFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gaps_hairengine_HairEngine_setTransformHE
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat);

/*
 * Class:     com_gaps_hairengine_HairEngine
 * Method:    resetTransformHE
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gaps_hairengine_HairEngine_resetTransformHE
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_gaps_hairengine_HairEngine
 * Method:    adjustHairPositionHE
 * Signature: (IFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gaps_hairengine_HairEngine_adjustHairPositionHE
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_gaps_hairengine_HairEngine
 * Method:    resetHairPositionHE
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gaps_hairengine_HairEngine_resetHairPositionHE
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_gaps_hairengine_HairEngine
 * Method:    enableShadowHE
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gaps_hairengine_HairEngine_enableShadowHE
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_gaps_hairengine_HairEngine
 * Method:    renderHE
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gaps_hairengine_HairEngine_renderHE
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_gaps_hairengine_HairEngine
 * Method:    setDermabrasionDegreeHE
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gaps_hairengine_HairEngine_setDermabrasionDegreeHE
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_gaps_hairengine_HairEngine
 * Method:    enableExpressionHE
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gaps_hairengine_HairEngine_enableExpressionHE
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_gaps_hairengine_HairEngine
 * Method:    changeExpressionHE
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gaps_hairengine_HairEngine_changeExpressionHE
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_gaps_hairengine_HairEngine
 * Method:    changeModifierHE
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gaps_hairengine_HairEngine_changeModifierHE
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_gaps_hairengine_HairEngine
 * Method:    changeHairColorHE
 * Signature: (IFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gaps_hairengine_HairEngine_changeHairColorHE
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_gaps_hairengine_HairEngine
 * Method:    resetExpressionHE
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gaps_hairengine_HairEngine_resetExpressionHE
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
